version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker-2:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [ web ]
    volumes: [ "./keys/worker:/concourse-keys"]
    links: [ web ]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: limit-active-containers,volume-locality,fewest-build-containers
      CONCOURSE_MAX_ACTIVE_CONTAINERS_PER_WORKER: 25
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker-3:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [ web ]
    volumes: [ "./keys/worker:/concourse-keys"]
    links: [ web ]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: limit-active-containers,volume-locality,fewest-build-containers
      CONCOURSE_MAX_ACTIVE_CONTAINERS_PER_WORKER: 25
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker-4:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [ web ]
    volumes: [ "./keys/worker:/concourse-keys"]
    links: [ web ]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: limit-active-containers,volume-locality,fewest-build-containers
      CONCOURSE_MAX_ACTIVE_CONTAINERS_PER_WORKER: 25
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker-5:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [ web ]
    volumes: [ "./keys/worker:/concourse-keys"]
    links: [ web ]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: limit-active-containers,volume-locality,fewest-build-containers
      CONCOURSE_MAX_ACTIVE_CONTAINERS_PER_WORKER: 25
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
